Gamefunctions fixes
hecoding/Pac-Man pull request #41
Opened 2017-04-02 15:11 UTC by J-888

fixes for issue #31 & naive implementation of smart moves

2017-04-02 18:51 UTC, hecoding approved these changes
qué tal funka? todo parece correcto

2017-04-02 18:55 UTC, J-888 commented
A priori aceptablemente bien. Los smartmoves algo mejor que los default, pero habria que pensar como mejorarlos algo mas. Tal vez en lugar de movimientos direccionales emplear movimientos relativos a pacman

2017-04-03 19:11 UTC, jorgevl approved these changes
Mola. La primera comprobación tho, no tiene en cuenta hacia donde mira el fantasma, no? La distancia de ese fantasma mas cercano es irreal si el fantasma no mira en la dirección que mas le conviene. Supongo que es aposta porque da igual para lo que nos interesa?

PS. Si es así le pondría un comentario diciendo que esa distancia en realidad no es real pero nos da igual.

2017-04-03 20:39 UTC, Jorjatorz requested changes

2017-04-03 20:39 UTC, Jorjatorz commented on src/pacman/game/Game.java
> +				if (pacmanDistanceToJunction <= distanceGhostToPacman)	//ghost is between junction and Pacman and facing Pacman
Esto siempre va a ser True para todo fantasma que este más alejado de Pacman que Pacman de la junction (en el peor de los casos serían tres fantasmas, todos menos el que hace false el if anterior `if (ghostDistanceToJunction > pacmanDistanceToJunction)`

2017-04-03 20:39 UTC, Jorjatorz commented on grammar/complete_grammar.bnf
> +                | isJunctionSafeUp
Yo aquí también meteria una `isJunctionSafe` que comprobase en la currentDirection del Pacman.

2017-04-03 20:39 UTC, Jorjatorz commented on src/pacman/game/Game.java
> +				return MOVE.NEUTRAL;	//unknown situation
En vez de dejar un movimiento neutral (e.g. que siga su camino actual) yo lo que haría es devolver la dirección opuesta a la actual que lleva (dado que es una situación desconocida sería mejor volver por donde ha venido)

2017-04-03 20:42 UTC, J-888 commented on src/pacman/game/Game.java
> +				return MOVE.NEUTRAL;	//unknown situation
La idea de esto es ayudar a pacman a girar en esquinas, si volvemos hacia atrás no se consigue nada

2017-04-03 20:45 UTC, J-888 commented on grammar/complete_grammar.bnf
> +                | isJunctionSafeUp
La idea es que pacman pueda girar en cualquier momento, aunque tiene bastante sentido que si hacia donde va se de la vuelta. Seria razonable solo si se implementan movimientos relativos

2017-04-04 17:58 UTC, Jorjatorz commented on src/pacman/game/Game.java
> +				return MOVE.NEUTRAL;	//unknown situation
Ya, pero si estas en una situacion desconocida (que seguramente sea un atasco) pues en vez de quedarse ahí parado que vuelva para atrás. Pero me es indiferente la verdad.

2017-04-04 18:01 UTC, Jorjatorz commented on grammar/complete_grammar.bnf
> +                | isJunctionSafeUp
Pero podría hacer algo en plan `if(!isJunctionSafe) getAwayFromClosest` pero como tú dices tiene más sentido con movimientos relativos.

2017-04-04 19:00 UTC, J-888 commented on src/pacman/game/Game.java
> +				return MOVE.NEUTRAL;	//unknown situation
La idea es que esto impide que haya atascos, por eso no se para

2017-04-04 19:02 UTC, J-888 commented on grammar/complete_grammar.bnf
> +                | isJunctionSafeUp
Al menos por el momento no lo veo

2017-04-05 10:51 UTC, merged